### ISSUE TITLE
ZeroDivisionError on statistics.harmonic_mean()

### ISSUE THREAD

**Issue by alexchowle** [avalente/appmetrics#10]
If you create a Histogram and record values in it that total to 0 (zero), the `statistics.harmonic_mean(data)` function causes a `ZeroDivisionError`.

To reproduce, record 0, 1, and -1 as values on the Histogram. Then call the Histogram's `get()` function

**Comment by avalente** [comment]
Hello, I am sorry but I'm not maintaining this repository anymore. It looks like the issue was solved in pr #9 . Please feel free to fork the repo, I'm sorry but currently I don't have time to work on it.
